export const Colors = {
    light: {
        text: '#000',
        background: '#fff',
        tint: '#2f95dc',
        tabIconDefault: '#ccc',
        tabIconSelected: '#2f95dc',
        card: '#f9f9f9',
        border: '#e0e0e0',
        riskLow: '#4CAF50',
        riskModerate: '#FFC107',
        riskMedium: '#FF9800',
        riskHigh: '#F44336',
        riskSevere: '#B71C1C',
    },
    dark: {
        text: '#fff',
        background: '#121212',
        tint: '#fff',
        tabIconDefault: '#ccc',
        tabIconSelected: '#fff',
        card: '#1E1E1E',
        border: '#333333',
        riskLow: '#4CAF50',
        riskModerate: '#FFC107',
        riskMedium: '#FF9800',
        riskHigh: '#F44336',
        riskSevere: '#B71C1C',
    },
};
